apiVersion: v1
kind: Service
metadata:
  name: drupal
  labels:
    app: drupal
spec:
  ports:
    - port: 80
  selector:
    app: drupal
    tier: frontend
  type: LoadBalancer
---
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: drupal
  labels:
    app: drupal
spec:
  replicas: 2
  selector:
    matchLabels:
      app: drupal
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: drupal
        tier: frontend
    spec:
      containers:
      - image: drupal:latest
        name: drupal
        env:
        - name: MYSQL_DATABASE
          value: mysqldata
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password
        ports:
        - containerPort: 80
          name: drupal
        volumeMounts:
        - name: drupal-storage
          mountPath: /var/www/html
      volumes:
      - name: drupal-storage
        persistentVolumeClaim:
          claimName: efs-drupal
      restartPolicy: Always